# Generated by Django 2.2.13 on 2020-08-15 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_cvpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvpost',
            name='job_duration',
            field=models.TextField(blank=True, null='True'),
            preserve_default='True',
        ),
    ]
