# Generated by Django 2.2.13 on 2020-08-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_cvpost_job_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvpost',
            name='job_duration',
            field=models.CharField(blank=True, max_length=200, null='True'),
        ),
    ]
