# Generated by Django 2.2.13 on 2020-08-15 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200816_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvpost',
            name='job_duration',
            field=models.CharField(max_length=200, null='True'),
        ),
    ]
